### ISSUE TITLE
Request <username>@legalese.io email addresses

### ISSUE THREAD

**Issue by virgil** [legalese-io/legalese-io.github.io#107]
I wish to create a Legalese company page on LinkedIn, Crunchbase, etc.  To do so I need a virgil@legalese.io email address.

Somewhat related, I've noticed the legalese.com, although it's registered, is currently not in use.

**Comment by mengwong** [comment]
i don't know if @wabisabiyo has owner access to Google Apps so i'm going to go ahead and pick this up.

**Comment by mengwong** [comment]
there are two ways to do this – as a mailing list with only one member, or as an alias.

mailing lists are archived and can be read by other project members.

aliases are not archived; messages cannot be seen by anyone other than the recipient.

which approach would be more valuable to the project?

**Comment by virgil** [comment]
Perhaps surprisingly, I like the idea of single-member mailing lists.
Employees just accept that anything sent through legalese.io is fair-game
to be indexed by the collective knowledge base.

**Comment by mengwong** [comment]
that would help with our CRM also because if somebody gets hit by a bus the other people can pick up where they left off.

**Comment by mengwong** [comment]
and if somebody goes on vacation, other people can be added to the mailing list.

**Comment by mengwong** [comment]
i would do mengwong@legalese.io that way but for legacy reasons that email address is already a firehose of confidential Adobe Echosign PDFs. Maybe I can fix that in the future.

**Comment by mengwong** [comment]
we would have to think hard about "forgot password" security considerations, because email is used as identity nowadays. so there is a privilege escalation path from somebody being on the project, to having access to the mailing list archives, to being able to identity-theft you, and then deregister the legalese.com domain.

**Comment by mengwong** [comment]
Hmm. How would a single-member mailing list send email as that identity? Maybe in practice this doesn't matter because the world only sends to the address, and doesn't care about messages coming from it. Let's try it and if this doesn't work we can switch back to an alias.

Even with an alias there would be some amount of overhead in setting up the ability to send mail from that address.

**Comment by sebdeckers** [comment]
Spoof it on outgoing emails, or does the domain have DKIM and such?

**Comment by mengwong** [comment]
well, virgil has received my email, so our little mailing list hack seems to work for the purpose originally specified in the issue description, so i'm going to close the issue, unless @virgil needs anything more?
