### ISSUE TITLE
Get TLS EV CERT

### ISSUE THREAD

**Issue by virgil** [legalese-io/legalese-io.github.io#191]
https://legalese.slack.com/files/virgil/F1SKZTC6N/ss_2016-07-18_at_19.52.02.png

As-is, our certificate would currently say, “Legalese PTE. LTD.” It would be nice if we could get this to say, “Legalese Inc.”  Or even "Legalese Limited" or "Legalese LTD."

Can @chiahli or @wabisabiyo get that to be our official title?  Once done, I can apply for the EV Cert.

**Comment by wabisabiyo** [comment]
@virgil No, it's not our official title because it's neither our official status nor non-official status. We're a private limited company. They're not just aesthetically different, they're legally different entities with differing legal connotations. 

See:
https://www.quora.com/Why-cant-a-Singapore-company-register-its-name-with-Inc-as-a-suffix 
https://www.acra.gov.sg/uploadedFiles/Content/Publications/Guides/CompanyNames.pdf

**Comment by virgil** [comment]
Okay.  Lets aim for Legalese Pte. Ltd.

**Comment by chiahli** [comment]
lol since it's acra autocomplete, not sure what we can do.

But i'm happy to write in to certsimple to ask.

**Comment by virgil** [comment]
Don't worry about it.  Being taken care of.

**Comment by chiahli** [comment]
lol i sent email to mike too :)

**Comment by virgil** [comment]
I've done every part I can do on my end.  All that remains is to answer the email registered as the admin contact for legalese.com

**Comment by virgil** [comment]
I've installed the HTTPS certificate, now I need to set the CNAME configuration for legalese.com for the HTTPS certificate to work.  However this is protected by 2FA which only the One True Meng has authorization for.

Meng: please login to dnsimple.com and change the CNAME and ALIAS record to: `shizuoka-16533.herokussl.com`

**Comment by virgil** [comment]
<img width="356" alt="ss 2016-07-26 at 16 31 33" src="https://cloud.githubusercontent.com/assets/81322/17131146/a8186406-534e-11e6-86a6-5813fc24976d.png">
Solved.
