### ISSUE TITLE
create roles and circles "org chart"

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#198]
in response from request by potential investor "who does what, show us your org chart"
1. find out if there exist open/free alternatives to glassfrog
2. maybe express our roles and circles in a spreadsheet
3. think about how to abstract the general case (all startups) from our case (legalese)

motivation for 3: https://twitter.com/balajis/status/750163292979535872

initial work behind item 2 may be
https://docs.google.com/spreadsheets/d/1w4TTBdP4-SxsGgpHYB_I1_5VyvhIl7BcbXS5m2UVLTE/edit#gid=366895701

remember: separate role from soul
http://janhoglund.eu/are-holacracy-and-sociocracy-teal/

**Comment by chiahli** [comment]
I would like us to consider using the valve model 
[Valve_Handbook_LowRes.pdf](https://github.com/legalese/legalese.github.io/files/381181/Valve_Handbook_LowRes.pdf)

for example:
"Team leads
Often, someone will emerge as the “lead” for a project. This person’s role is not a traditional managerial one. Most often, they’re primarily a clearinghouse of information. They’re keeping the whole project in their head at once so that people can use them as a resource to check decisions against. The leads serve the team, while acting as centers for the teams."

**Comment by chiahli** [comment]
Another example could be:
“T-shaped” people.
That is, people who are both generalists (highly skilled at
a broad set of valuable things—the top of the T) and also experts (among the best in their field within a narrow discipline—the vertical leg of the T).

We could list our skills/expert areas so that the team members know who to tap on. And also we could list the areas where we wish to broaden our skills to.

**Comment by virgil** [comment]
https://app.glassfrog.com/organizations/4050

**Comment by virgil** [comment]
If we are showing our GlassFrog to seedplus, I am presuming this ticket is satisfied and can be closed.
