### ISSUE TITLE
xmls of documents fail to appear when running Legalese tutorial 

### ISSUE THREAD

**Issue by chiahli** [legalese-io/legalese-io.github.io#210]
Error message: 
TypeError: Expected argument of type object, but instead had type undefined.

**Comment by waitwtfff** [comment]
This error occurs while evaluating the Series Seed template, exactly at the line https://github.com/legalese/legalese.github.io/blob/master/templates/seriesseed.com/seriesseed_investment_agreement_sg.xml#L93, because `data.parties.key_holder` in https://github.com/legalese/legalese.github.io/blob/master/templates/seriesseed.com/seriesseed_investment_agreement_sg.xml#L90 is undefined.

Upon fixing this error, another error occurs: the variables `f_commencement`, `f_unrestricted_current`, ... `acceleration` at https://github.com/legalese/legalese.github.io/blob/master/templates/seriesseed.com/seriesseed_investment_agreement_sg.xml#L108-L113 are all undefined.

The PDFs can be successfully generated after these two errors are fixed.
