### ISSUE TITLE
Buy L4.chat and L4LANG.ORG

### ISSUE THREAD

**Issue by virgil** [legalese-io/legalese-io.github.io#244]
L4.chat will host the bulletin board, and l4lang will for now redirect to Legalese.com .  I believe this is the correct branding decision.   We don't need l4lang.org yet, but we will within the next 1-2 years.  And it's cheap to register and prevents someone from squatting it.

**Comment by virgil** [comment]
I have purchased L4.CHAT.  I presume I'll one day be reimbursed, but I suppose I don't have to.

In the mean time, I do suggest that @wabisabiyo purchase L4LANG.ORG .

**Comment by wabisabiyo** [comment]
Will purchase whichever domain is necessary when the time comes - after the relevant circles have weighed in on the issue.

Let the records also reflect that the l4.chat purchase mentioned in the above was not compliant with Legalese #finance readme and compensation protocols.

**Comment by mengwong** [comment]
I believe the procedure is something like

1. somebody proposes domain and cost

2. circle discusses and agrees which domains to buy

3. relevant circle member logs in to the existing clause account at whatever registrar we use, to then make the purchase, adding the desired domain to our list of existing domains.

if the domain has already been purchased on a Grace Hopper Initiative then step 3 would be to make a transfer, instead of buying it anew, but the previous two steps would still be required to establish intent.
